# -*- coding: utf-8 -*-
"""GOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3IdlZ0qbnfy2hBNtG4jWVaW3Q9NII4-
"""

import numpy as np
import pandas as pd

pwd

battle = pd.read_csv(r"/content/sample_data/battles.csv.xls")

battle.head()

battle.shape

battle.rename(columns={'defender_1' : 'primary_defender'},inplace=True)

battle['attacker_king'].value_counts()

battle['location'].value_counts()

import seaborn as sns
from matplotlib import pyplot as plt

sns.set(rc={'figure.figsize':(13,5)})
sns.barplot(x='attacker_king',y='attacker_size',data = battle)
plt.show()

sns.set(rc={'figure.figsize':(13,5)})
sns.barplot(x='defender_king',y='defender_size',data = battle)
plt.show()

sns.countplot(x= battle['attacker_king'],hue=battle['battle_type'])
plt.show()

death=pd.read_csv(r'/content/sample_data/character-deaths.csv.xls')
death.head()

death.shape

death['Gender'].value_counts()

death['Nobility'].value_counts()

sns.countplot(death['Death Year'])
plt.show()

sns.set(rc={'figure.figsize':(30,10)})
sns.countplot(death['Allegiances'])
plt.show()

